---
- hosts: apache
  remote_user: root
  vars:
    http_port: 80
    max_client: 300 
  tasks:
  - name: installing modssl server
    yum:
      name: mod_ssl
      state: latest
  - name: iptables flush
    command: iptables -F
  - name: restart the apache service 
    service:
      name: httpd
      state: restarted 
      enabled: yes

