---
- hosts: mariadb
  remote_user: root
  vars:
    mariadb_port: 3306 
    max_client: 100 
  tasks:
  - name: installing mariadb server
    yum:
      name: mariadb-server,mariadb,MySQL-python
      state: latest
