---
- hosts: nfs
  remote_user: root
  tasks: 
    - name: Install configuration file
      template: src=/etc/ansible/templates/exports.j2 dest=/etc/exports owner=root group=root

    - name: restart rpcbind server
      service: name=rpcbind state=started
     
    - name: restart nfs server
      service: name=nfs-server state=started

    - name: iptables flush
      command: iptables -F
   
    - name: export
      command: exportfs -r



