---
- hosts: smtp
  remote_user: root
  vars:
    max_client: 300 
  tasks:
  - name: starting postfix server service 
    service:
      name: postfix
      state: started 
      enabled: yes

  - name: disable selinux
    lineinfile: dest=/etc/selinux/config
                regexp='^SELINUX='
                line='SELINUX=disabled'
                state=present

  - name: iptables flush
    command: iptables -F
